
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export const INCREMENT_ENTHUSIASM_SUCCESS = 'INCREMENT_ENTHUSIASM_SUCCESS';
export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export const GET_REPOS = 'GET_REPOS';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
